/* Optional: install Playwright + Chromium; start app.py; node tests/browser-check.cjs */
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=process.env.NODE_MODULES_PATH?require(process.env.NODE_MODULES_PATH+'/playwright'):require('playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const errors=[],flows=[];
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8767');await page.locator('#login-form').waitFor();await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();assert.match(await page.locator('main').innerText(),/build-service/);flows.push('Permission findings and known unused grant');await page.screenshot({path:path.join(root,'docs/workspace.png'),fullPage:true,style:'#toast{visibility:hidden}'});
await page.getByRole('button',{name:'Access logs',exact:true}).click();await page.locator('#log-form').waitFor();await page.locator('#principal').selectOption('report-service');await page.getByRole('button',{name:'Filter logs',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#log-results')?.textContent.includes('report-service'));assert.ok(!(await page.locator('#log-results').innerText()).includes('sales-1'));flows.push('SQL log filtering');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download all logs · CSV',exact:true}).click();await(await download).saveAs(path.join(root,'docs/browser-export.csv'));flows.push('CSV export');
await page.getByRole('button',{name:'Policy validation',exact:true}).click();await page.getByRole('button',{name:'Run paired replay',exact:true}).click();await page.getByRole('button',{name:'Download evaluation JSON',exact:true}).waitFor();flows.push('Paired policy replay and metric display');await page.screenshot({path:path.join(root,'docs/evaluation.png'),fullPage:true,style:'#toast{visibility:hidden}'});
await page.locator('#department_boundary').uncheck();await page.getByRole('button',{name:'Save policy version',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.pill')].some(x=>x.textContent==='v2'));await page.getByRole('button',{name:'Run paired replay',exact:true}).click();await page.waitForFunction(()=>document.querySelector('table')?.textContent.includes('Candidate v2'));flows.push('Candidate policy version change');
await page.getByRole('button',{name:'Review report',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#report-text')?.textContent.includes('Detailed evidence'));assert.match(await page.locator('#report-text').innerText(),/policy v2/);const reportDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download Markdown report',exact:true}).click();await(await reportDownload).saveAs(path.join(root,'docs/browser-review.md'));flows.push('Report generation and download');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Permission findings',exact:true}).click();await page.getByRole('heading',{name:'Unused permissions',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(root,'docs/mobile.png'),fullPage:true,style:'#toast{visibility:hidden}'});flows.push('Mobile layout without document overflow');assert.equal(errors.length,0);fs.writeFileSync(path.join(root,'docs/browser-results.json'),JSON.stringify({flows,errors,passed:true},null,2));console.log('PASS',flows.length,'browser flows');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
