'use strict';
let state,csrf='',view='findings',busy=false,logFilter='';
const root=document.querySelector('#app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'N/A':(v*100).toFixed(1)+'%';
const lens='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.3"/><path d="m15.5 15.5 5 5M7 10.5h7M10.5 7v7" stroke="currentColor" stroke-width="1.3"/></svg>';
const pages={
  findings:{nav:'Permission findings',title:'Review access evidence',description:'Trace broad permissions and unusual activity back to the records that support them.'},
  logs:{nav:'Access logs',title:'Explore access events',description:'Inspect individual decisions across human and service identities.'},
  evaluation:{nav:'Policy validation',title:'Validate policy changes',description:'Compare observed decisions with candidate controls on the same evidence window.'},
  report:{nav:'Review report',title:'Prepare a policy review',description:'Bring the findings, proposed actions, and replay results into one reviewable record.'}
};
function toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.add('hidden'),4000);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});const out=await r.json();if(!r.ok)throw Error(out.error);return out;}
function run(fn){return async e=>{e?.preventDefault();if(busy)return;busy=true;const trigger=e?.currentTarget;const button=trigger?.tagName==='BUTTON'?trigger:trigger?.querySelector('button[type="submit"]');if(button){button.disabled=true;button.setAttribute('aria-busy','true');}try{await fn();}catch(err){toast(err.message);}finally{busy=false;if(button?.isConnected){button.disabled=false;button.removeAttribute('aria-busy');}}};}
async function refresh(){state=await api('state');csrf=state.csrf;render();}
function login(){root.innerHTML=`<div class="login-wrap"><section class="login-story"><div><div class="brand"><span class="mark">${lens}</span>Policy Lens</div><h1>Read the evidence.<br>Review the policy.</h1><p>Analyze access logs, find reviewable permissions, and measure the impact of proposed controls.</p></div><p>Offline analysis · Synthetic data · No live access changes</p></section><main id="main" class="login-form" tabindex="-1"><p class="eyebrow">ACCESS ANALYSIS LAB</p><h2>Open the analysis lab</h2><p class="muted">Security administrator workspace</p><form id="login-form"><div class="field"><label for="name">Username</label><input id="name" value="admin" autocomplete="username" required></div><div class="field"><label for="password">Password</label><input id="password" type="password" value="DemoPass!2026" autocomplete="current-password" required></div><button class="primary" type="submit">Sign in</button><div id="login-error" class="error-text" role="alert"></div></form><p class="login-foot">Demo: admin / DemoPass!2026</p></main></div>`;root.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const r=await api('login',{name:root.querySelector('#name').value,password:root.querySelector('#password').value});csrf=r.csrf;await refresh();}catch(err){root.querySelector('#login-error').textContent=err.message;}};}
function table(headers,rows,{label='Evidence records',className='',decisions=false}={}){
  return `<div class="table-wrap ${className}" tabindex="0" role="region" aria-label="${esc(label)}"><table aria-label="${esc(label)}"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td>${decisions&&i===r.length-1?`<span class="decision decision-${c==='allow'?'allow':'deny'}">${esc(c)}</span>`:esc(c)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}">No matching evidence.</td></tr>`}</tbody></table></div>`;
}
function panelHeading(index,title,badge=''){return `<div class="panel-head"><div><span class="section-index">${esc(index)}</span><h2>${esc(title)}</h2></div>${badge?`<span class="pill">${esc(badge)}</span>`:''}</div>`;}
function sparkline(){
  const days=state.overview.days,max=Math.max(...days.map(d=>d.volume),1);
  return `<div class="sparkline"><svg viewBox="0 0 150 42" role="img" aria-label="Daily access volume and unsafe allows across the 30-day synthetic window"><title>Gray: all access events. Copper: unsafe allows. Each bar represents one day.</title>${days.map((d,i)=>{const h=d.volume/max*40,u=d.unsafe_allows/max*40;return `<rect class="volume-bar" x="${i*5}" y="${42-h}" width="3" height="${h}"/><rect class="unsafe-bar" x="${i*5}" y="${42-u}" width="3" height="${u}"/>`;}).join('')}</svg><p class="muted">D01–D30 · DAILY VOLUME</p></div>`;
}
function findings(){
  const f=state.findings;
  const exposure=(items)=>table(['Identity / resource','Events','Example ID'],items.map(x=>[x.principal+' / '+x.resource,x.count,'#'+x.example_event]),{label:'Successful cross-department access',className:'evidence-table'});
  return `<div class="context-line"><span><strong>Evidence queue</strong> · ${f.cross_department_access.length} cross-department groups / ${f.unused_permissions.length} unused grants</span><span>Review candidates · No automatic revocation</span></div>
  <div class="evidence-layout"><div class="evidence-main">
    <section class="panel">${panelHeading('01 / EXPOSURE','Cross-department exposure',f.cross_department_access.length+' GROUPS')}<p class="panel-description">Successful access to resources outside the identity’s department.</p>${exposure(f.cross_department_access)}<div class="table-footer"><p class="muted">Example IDs link the finding to its source evidence.</p><button class="text-button" data-view="logs">Open access logs →</button></div></section>
    <section class="panel">${panelHeading('02 / DATA MOVEMENT','Sensitive exports',f.sensitive_exports.length+' GROUPS')}<p class="panel-description">Observed exports of restricted or confidential resources.</p>${table(['Identity / resource','Events','Example ID'],f.sensitive_exports.map(x=>[x.principal+' / '+x.resource,x.count,'#'+x.example_event]),{label:'Sensitive export evidence',className:'evidence-table'})}</section>
  </div><aside class="review-rail" aria-label="Review candidates and analysis method">
    <section class="panel">${panelHeading('03 / ENTITLEMENTS','Unused permissions',f.unused_permissions.length+' CANDIDATES')}<p class="panel-description">No successful use in this window. Confirm business need before removing a grant.</p><div class="grant-list">${f.unused_permissions.map(x=>`<div class="grant"><strong>${esc(x.principal)}</strong><p class="grant-resource">${esc(x.resource)} / ${esc(x.action)}</p><button class="text-button" data-view="logs" data-identity="${esc(x.principal)}" aria-label="Inspect ${esc(x.principal)} events">Inspect identity events →</button></div>`).join('')||'<p class="muted">No unused permissions observed.</p>'}</div></section>
    <section class="panel">${panelHeading('04 / ACTIVITY','Hourly volume spikes','HEURISTIC')}${f.volume_spikes.map(x=>`<div class="signal-detail"><strong>${esc(x.principal)}</strong><div class="signal-readout"><span>${esc(x.count)}</span><small>EVENTS / THRESHOLD ${esc(x.threshold)}</small></div><p class="muted">Day ${esc(x.day)} · ${String(x.hour).padStart(2,'0')}:00</p><button class="text-button" data-view="logs" data-identity="${esc(x.principal)}" aria-label="Review ${esc(x.principal)} activity">Review identity activity →</button></div>`).join('')||'<p class="muted">No volume spikes observed.</p>'}</section>
    <section class="methods"><p class="eyebrow">METHOD NOTE</p><h3>Signals require context.</h3><p>The spike threshold is max(10, average hourly rate + 4√rate). Unusual activity is a review signal, not proof of compromise. All records are fictional.</p></section>
  </aside></div>`;
}
function logs(){return `<section class="panel logs-panel">${panelHeading('EVENT EXPLORER','Access event explorer','2,400 RECORDS')}<form id="log-form" class="inline-form"><div class="field"><label for="principal">Identity</label><select id="principal"><option value="">All identities</option>${state.principals.map(p=>`<option ${p===logFilter?'selected':''}>${esc(p)}</option>`).join('')}</select></div><div class="field"><label for="decision">Observed decision</label><select id="decision"><option value="all">All decisions</option><option value="allow">Allowed</option><option value="deny">Denied</option></select></div><button class="primary" type="submit">Filter logs</button></form><div class="log-summary"><p id="log-count" role="status" aria-live="polite">Loading evidence…</p><button class="text-button" id="export-csv">Download all logs · CSV</button></div><div id="log-results" class="spaced"></div><p class="muted spaced">Showing up to 100 matching events. The CSV contains all 2,400 records, including events outside the current filter.</p></section>`;}
const names={department_boundary:'Department boundary',managed_device:'Managed device requirement',deny_high_risk:'High-risk denial',sensitive_export:'Sensitive export restriction'};
const descriptions={department_boundary:'Limit non-admin access to the identity’s department and shared resources.',managed_device:'Require a managed device for non-public resources.',deny_high_risk:'Deny events with a high-risk signal.',sensitive_export:'Restrict exports from confidential and restricted resources.'};
function evaluation(){
  const e=state.evaluation,stale=e&&e.version!==state.policy.version;
  const metrics=[['False allows','false_allow'],['False denies','false_deny'],['Deny precision','precision'],['Deny recall','recall'],['Accuracy','accuracy'],['Mean decision time · µs','mean_latency_us']];
  const value=(variant,key)=>['precision','recall','accuracy'].includes(key)?pct(variant[key]):key==='mean_latency_us'?variant[key].toFixed(2):variant[key];
  return `<div class="workspace"><section class="panel">${panelHeading('01 / POLICY DESIGN','Candidate controls','v'+state.policy.version)}<p class="panel-description">Select controls, save a version, then replay it against the observed access window.</p><form id="policy-form"><div class="checks">${Object.entries(names).map(([k,n])=>`<div class="check"><input type="checkbox" id="${k}" aria-describedby="${k}-description" ${state.policy.rules[k]?'checked':''}><div><label for="${k}">${n}</label><span id="${k}-description" class="control-description">${descriptions[k]}</span></div></div>`).join('')}</div><div class="policy-actions"><button type="submit">Save policy version</button><button class="primary" id="evaluate" type="button">Run paired replay</button></div><p id="policy-draft" class="muted spaced" role="status" aria-live="polite">Version ${state.policy.version} is ready to replay.</p></form><div class="notice spaced">Observed decisions use the legacy entitlement snapshot. Candidate decisions are scored against synthetic desired-policy labels. <strong>Positive class = deny.</strong></div><div class="spaced"><p class="query-label">MEASUREMENT / SQL</p><pre class="code">SELECT SUM(predicted_deny = 0\n AND expected_deny = 1)\n AS false_allow\nFROM replay\nWHERE run_id = ?;</pre></div></section>
  <section class="panel impact-panel">${panelHeading('02 / PAIRED REPLAY','Measured policy impact',e?'RUN '+e.run_id:'AWAITING REPLAY')}${stale?`<div class="notice spaced"><strong>Saved policy has changed.</strong> These results belong to version ${e.version}. Run a new replay to evaluate version ${state.policy.version}.</div>`:''}${e?`<p class="panel-description">Same ${e.events.toLocaleString()} events. Two sets of access decisions.</p>${table(['Metric','Observed','Candidate v'+e.version],metrics.map(([n,k])=>[n,value(e.observed,k),value(e.candidate,k)]),{label:'Observed and candidate policy metrics'})}<div class="change-readout"><strong>${e.changed_decisions.toLocaleString()}</strong><span>changed decisions<br><span class="muted">of ${e.events.toLocaleString()} observed events</span></span></div><p class="muted spaced">Candidate accuracy · Wilson 95% interval: ${pct(e.candidate.accuracy_interval_95[0])}–${pct(e.candidate.accuracy_interval_95[1])}. Decision latency excludes HTTP and database overhead.</p><button id="export-eval" class="spaced">Download evaluation JSON</button>`:'<div class="empty"><span class="empty-number">—</span><h3>No replay results yet</h3><p>Save a candidate policy and run a paired replay to measure incorrect allows, incorrect denies, and decision accuracy.</p></div>'}<p class="muted spaced">Offline replay on synthetic labels. Results are not a production security benchmark or a live A/B experiment.</p></section></div>`;
}
function report(){return `<div class="report-layout"><aside class="report-outline"><h2>The review record</h2><ol><li>Observation window</li><li>Permission findings</li><li>Supporting evidence</li><li>Proposed review actions</li><li>Latest policy replay</li><li>Limitations</li></ol><button id="export-report" class="primary">Download Markdown report</button><p class="muted spaced">A portable record for review with an engineering team. Includes fictional evidence and the latest saved replay.</p></aside><section class="panel report-panel"><div class="panel-head"><div><span class="section-index">REVIEW DOCUMENT / MARKDOWN</span><h2>Evidence-backed policy review</h2></div><span class="pill">READ ONLY</span></div><pre id="report-text" class="code" tabindex="0" aria-label="Policy review report">Loading the review record…</pre></section></div>`;}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function render(){
  const t=state.overview.totals,p=pages[view];
  root.innerHTML=`<div class="shell"><aside class="sidebar"><div><div class="brand"><span class="mark">${lens}</span>Policy Lens</div><p class="brand-subtitle">Access analysis lab</p></div><div><p class="nav-label">Analysis workspace</p><nav class="nav" aria-label="Main navigation">${Object.entries(pages).map(([k,p],i)=>`<button data-view="${k}" aria-label="${p.nav}" class="${view===k?'active':''}" ${view===k?'aria-current="page"':''}><span class="nav-index" aria-hidden="true">0${i+1}</span>${p.nav}</button>`).join('')}</nav></div><div class="sidebar-foot"><p class="eyebrow">EVIDENCE COLLECTION</p><h3>Northstar / 30 days</h3><p class="muted">30-day synthetic window<br>12 human and service identities</p></div></aside>
  <main id="main" class="main" tabindex="-1"><header class="topline"><p class="eyebrow">SECURITY ANALYTICS / OFFLINE REVIEW</p><div class="top-actions"><span class="lab-status">Offline workspace</span><button id="logout">Sign out</button></div></header><div class="page-heading"><div><h1>${p.title}</h1><p>${p.description}</p></div><div class="page-reference"><strong>NORTHSTAR</strong>WINDOW / D01–D30</div></div>
  <div class="metrics-strip" aria-label="Evidence window totals"><div class="metric metric-volume"><div><p class="meta-label">Access events</p><div class="metric-value">${t.events.toLocaleString()}</div><p class="muted">30-day observation window</p></div>${sparkline()}</div><div class="metric"><p class="meta-label">Identity permissions</p><div class="metric-value">${t.entitlements}</div><p class="muted">Legacy entitlement snapshot</p></div><div class="metric metric-risk"><p class="meta-label">Observed unsafe allows</p><div class="metric-value">${t.unsafe_allows}</div><p class="muted">Against desired-policy labels</p></div></div>${({findings,logs,evaluation,report}[view])()}<footer class="page-foot"><span>SYNTHETIC EVIDENCE / SEED ${state.overview.seed}</span><span>No live access changes · Offline policy analysis</span></footer></main></div>`;
  bind();
}
async function fillLogs(){
  const principal=root.querySelector('#principal').value,decision=root.querySelector('#decision').value;
  logFilter=principal;
  const r=await api('logs',{principal,decision});
  if(view!=='logs')return;
  root.querySelector('#log-count').textContent=`${r.shown} shown / ${r.matching_total} matching events`;
  root.querySelector('#log-results').innerHTML=table(['ID / day / hour','Identity','Resource','Action','Device / risk','Observed'],r.events.map(e=>[e.id+' / '+e.day+' / '+String(e.hour).padStart(2,'0')+':00',e.principal,e.resource,e.action,e.device+' / '+e.risk,e.observed_allow?'allow':'deny']),{label:'Matching access events',decisions:true});
}
function bind(){
  root.querySelectorAll('[data-view]').forEach(b=>b.onclick=run(async()=>{view=b.dataset.view;if(b.dataset.identity)logFilter=b.dataset.identity;else if(view==='logs')logFilter='';await refresh();root.querySelector(`.nav [data-view="${view}"]`)?.focus({preventScroll:true});}));
  root.querySelector('#logout').onclick=run(async()=>{await api('logout',{});state=null;csrf='';login();});
  root.querySelector('#log-form')?.addEventListener('submit',run(fillLogs));
  if(view==='logs')fillLogs().catch(e=>toast(e.message));
  root.querySelector('#export-csv')?.addEventListener('click',run(async()=>download((await api('export')).csv,'policy-lens-access-events.csv','text/csv')));
  root.querySelector('#policy-form')?.addEventListener('submit',run(async()=>{const rules={};Object.keys(names).forEach(k=>rules[k]=root.querySelector('#'+k).checked);await api('policy',{rules});await refresh();root.querySelector('#evaluate').focus({preventScroll:true});toast('Candidate version saved. No live permissions changed.');}));
  Object.keys(names).forEach(k=>root.querySelector('#'+k)?.addEventListener('change',()=>{const dirty=Object.keys(names).some(key=>root.querySelector('#'+key).checked!==state.policy.rules[key]);root.querySelector('#evaluate').disabled=dirty;root.querySelector('#policy-draft').textContent=dirty?'Unsaved controls. Save a version before replaying.':`Version ${state.policy.version} is ready to replay.`;}));
  root.querySelector('#evaluate')?.addEventListener('click',run(async()=>{await api('evaluate',{});await refresh();root.querySelector('#evaluate').focus({preventScroll:true});toast('Paired replay complete.');}));
  root.querySelector('#export-eval')?.addEventListener('click',()=>download(JSON.stringify(state.evaluation,null,2),'policy-lens-evaluation.json','application/json'));
  root.querySelector('#export-report')?.addEventListener('click',run(async()=>download((await api('report')).markdown,'policy-lens-review.md','text/markdown')));
  if(view==='report')api('report').then(r=>{if(root.querySelector('#report-text'))root.querySelector('#report-text').textContent=r.markdown;}).catch(e=>toast(e.message));
}
refresh().catch(()=>login());
